# @package eval.tofu
# NOTE: the above line is not a comment, but sets the package for config. See https://hydra.cc/docs/upgrades/0.11_to_1.0/adding_a_package_directive/

defaults: # include all defined metrics files
  - tofu_metrics: # When you import a metric here, its configuration automatically populates the
  # metric key below, enabled by the @package directive at the top of each configuration file.
    - forget_Truth_Ratio
    - retain_Truth_Ratio
    - forget_quality
    - forget_Q_A_Prob
    - forget_Q_A_ROUGE
    - forget_Q_A_gibberish
    - forget_Q_A_PARA_Prob
    - forget_Q_A_PARA_ROUGE
    - forget_Q_A_PERT_Prob
    - forget_Q_A_PERT_ROUGE
    - retain_Q_A_Prob
    - retain_Q_A_ROUGE
    - retain_Q_A_PARA_Prob
    - retain_Q_A_PERT_Prob
    - ra_Q_A_Prob
    - ra_Q_A_ROUGE
    - ra_Q_A_PERT_Prob
    - ra_Q_A_Prob_normalised
    - ra_Truth_Ratio
    - wf_Q_A_Prob
    - wf_Q_A_ROUGE
    - wf_Q_A_PERT_Prob
    - wf_Q_A_Prob_normalised
    - wf_Truth_Ratio
    - model_utility # populated in the metrics key as metrics.model_utility
    - privleak
    - extraction_strength
    - exact_memorization
    - mia_min_k_plus_plus
    - mia_min_k
    - mia_loss
    - mia_zlib
    - mia_gradnorm
    #- mia_reference 


handler: TOFUEvaluator
output_dir: ${paths.output_dir} # set to default eval directory
metrics: {} # lists a mapping from each evaluation metric to its config 
# populated through the first (@package) line in each metric config
overwrite: false
forget_split: forget10
holdout_split: holdout10
retain_logs_path: null
question_key: "question" # Specifies which key to use during forget and retain evaluations (e.g., "question" or "paraphrased_question")
batch_size: 32